### PR TITLE
 Kurdish support  and second way of arabic to support extra fonts

### PR DESCRIPTION
**Pull request by ravarage**
I applied all of your suggestion, and fix small bugs that comes with it, now it should work without issue

### CODE REVIEW

**Comment by mpcabd** [comment]
Thanks @ravarage, because I cannot understand Kurdish and cannot verify this works, could you write a couple of unit tests like [these ones](https://github.com/mpcabd/python-arabic-reshaper/blob/master/arabic_reshaper/tests/test_002_reshaping.py)? This way we can ensure Kurdish support is tested well and won't break over time.

**Comment by ravarage** [comment]
sorry for being late, I didn't have time for scratch my head, all done now, Kurdish is basically Arabic script, without harakat, and some extra chart that doesnt follow standard fonts, if arabic works I am pretty sure Kurdish will works, I added few word just to be sure

**Comment by mpcabd** [comment]
Great work, thanks a lot for your support!

**Comment by mpcabd** [comment]
I will be making a new release soon with this.

**Pull request merged**
