### PR TITLE
fix for ZWJ

### PR DESCRIPTION
**Pull request by leomoon**
Zero-width Joiner support so you can write things like [ ه‍ ]

### CODE REVIEW

**Comment by mpcabd** [comment]
Hello

Can you check 75df1ed1 and run it against your use cases and tell me if it behaves as expected?

**Comment by leomoon** [comment]
Yes it works as expected.

I also wanted to share my test case file. I made this to test for shaping, harekats, and bidi. It might be useful to you:
https://www.dropbox.com/s/5eld6s4kepiux4z/testCases.txt

**Comment by mpcabd** [comment]
I've tested all my use cases in browsers, and I think the current implementation matches what browsers do, you can use this https://codepen.io/mpcabd/full/MOQeNQ/ to test and play a bit.

**Comment by leomoon** [comment]
I know how to replicate using your link.

Try [ZWJ]+[ب]: This should give the FINAL form not isolated.
And try [ZWJ]+[ب]+[ZWJ]: This should give the MEDIAL form not initial.

I can explain more if you need. I think I'm not explaining well.

And here is an [screenshot of a these characters by just using ZWJs](https://www.dropbox.com/s/aqb9vzlv1t7pje5/zwjTypes.jpg) using notepad.

**Comment by mpcabd** [comment]
Hello,

I saw your video, and updated the codepen, and indeed the font was playing games with my eyes, I've fixed that, please check the [latest release](https://github.com/mpcabd/python-arabic-reshaper/releases/latest) it now matches the codepen after I changed the font.

**Comment by leomoon** [comment]
PERFECT.

**Pull request closed without merging**
